name = "SimpleDiscontinuousGalerkin"
uuid = "1c8e7e25-3265-4959-9fcf-9ce6764f3290"
authors = ["Joshua Lampert <joshua.lampert@uni-hamburg.de> and contributors"]
version = "0.1.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SimpleUnPack = "ce78b400-467f-4804-87d8-8f486da07d0a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
SummationByPartsOperators = "9f78cca6-572e-554e-b819-917d2f1cf240"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
TrixiBase = "9a0f1c46-06d5-4909-a5a3-ce25d3fa3284"

[compat]
LinearAlgebra = "1"
Reexport = "1.2"
SimpleUnPack = "1.1.0"
StaticArrays = "1.9"
SummationByPartsOperators = "0.5.78"
TimerOutputs = "0.5.23"
TrixiBase = "0.1.3"
julia = "1.10"
